install.sh

As of now, the install script assumes `.zshrc` lives at `$HOME/.zshrc`, which is a fairly reasonable assumption.
With that said, I think it's common for users to set `$ZDOTDIR` in their `$HOME/.zshenv` file so that all of the zsh config can be stored in a standard location like `$HOME/.config`. This PR just adds support for that use case. 
The additional check to make sure `$ZDOTDIR/.zshrc` exists seems redundant since the whole point of setting `$ZDOTDIR` is so that you can store `.zshrc` in there. I've added it *just in case* someone doesn't store their `.zshrc` in there. Please let me know if the check should be removed. 
I'd also be more than happy to add documentation for it if need be. 
As a final note, the usage of `$ZDOTDIR` is common among the zsh users that I know, but if it's a …

Check zdotdir

---

install.sh
zap.zsh

Some cleanup of the variables.
I mentioned in some commit that we might want to change from using `#!/bin/sh` to either bash or zsh since some language features that we currently use aren't POSIX compliant. Maybe go for Zsh?

Misc features and fixes

---

doc.txt
install.sh
zap.zsh

```
$ zap update
$ zap delete
$ zap pause
$ zap unpause
$ zap -h
```
Zap Version Option Still to Come

feat: Update & Delete Plugin Options

---

doc.txt

short and long "flagged" options in the same line

fix: duplicated lines in `doc.txt`

---

zap.zsh

wen calling `zapplug` if asecond arg is given it is used to checkout that particular commit
```sh
zapplug "zap-zsh/zap" f0f99ec6268adcf4e43766633621bad9d2cb1d0d
```

feat: add "pin to commit" functionality

---

.editorconfig
.github/workflows/pre-commit.yml
.pre-commit-config.yaml
README.md
install.sh
zap.zsh

Auto formatting!
This PR adds our first CI integration.
Everyone will after this PR need to format their code with `shfmt -w .` for CI to be happy.
Closes #38

Add auto formatting and CI!

---

zap.zsh

Fixing issue #35 and now instead of typing the entire plugin name one can just type a letter [a], or a number [0,1,2 ...] to prevent the frustration of ty[os

fix|update: Update, Pause, Unpause, Delete functions

---

doc.txt
zap.zsh

Issues: #46 for flags & #43 for blank plugins due to commenting
```
$ zap --update
$ zap -u
...
```

Simpler flag options for `zap` command

---

zap.zsh

- removed `_try_source`, I think it's actually useless
- changed `plugin_name` declaration, I it's way more readable
- duplicated `plugin_name` variable

fix: a bunch of modifications

---

zap.zsh

I've also added `--follow-symlinks` to the `sed` commands.
A lot of people use dotfile repos and create symlinks. I think it makes more sense to have the original changed than to break the link (the backup is still created).
I was making changes to my `.zshrc` in my repo and nothing was being picked up as the link broke, it was quite confusing .

Feat/don't ask unneeded input on (de)activate

---

.gitignore
doc.txt
zap.zsh

The regex to support activate and deactivate was getting a little complicated
deactivating a plugin can be done by commenting it out, activating by removing the comment
zap will ask the user after updating if they would like to remove plugins no longer in their config

feat: plugins will be cleaned up after update, removed activate, deactivate, remove

---

zap.zsh

This is a quality-of-life change useful for cloning plugins with a
(semi-)big commit history, for example romkatv/powerlevel10k. It may
speed up downloading the plugin for the first time in those cases.

feat: clone just as much as needed

---

install.sh
zap.zsh

Added support for plugins with name `zsh-<plugin>/<plugin>.zsh` for plugins like `"Tarrasch/zsh-autoenv"`.
Removed the check for `.zshrc` when `$ZDOTDIR` is set, since the default becomes $HOME.

feat: modify _try_source and ZOTDIR with .zshrc

---

install.sh

It avoids that beginners zsh, or maybe shell, users have to think about where to put that line in their zshrc.

Source zap at the beginning of the zshrc

---

.gitignore
zap.zsh

Consistently use the ZAP_DIR and ZAP_PLUGIN_DIR environment variables defined once to act as constants.

Consistently use ZAP_DIR and ZAP_PLUGIN_DIR

---

install.sh
zap.zsh

`ZDOTDIR` is allowing to change directory for `.zshrc` file. It should be set in `/env/zshev` or `~/.zshev`
Reading .zshenv is done automatically only in zsh shell. Not all systems are symlinking /bin/sh -> zsh, some are pointing it to bash (by default) some more exotic ones can point to whatever.
should fix issue zap-zsh/zap#70

Fix: install.sh sh->zsh shebang to guarantee read .zshenv

---

install.sh
zap.zsh

Set the hashbang to '/usr/bin/env zsh', not '/bin/env zsh', so it works on MacOS aswell as Linux

fix: correct hashbang

---

install.sh

Fix: fix MacOS `sed` compatibility and backup user config
This solves #91 and #95

Fix: fix MacOS `sed` compatibility and backup user config

---

zap.zsh

When executing `plug 'pabloariasal/zfm'` a `permission denied` error is thrown.
This is caused by the last line of the `zfm.zsh` file:
`"$@"`
via Zap this translates to:
`$HOME/.local/share/zap/plugins/zfm zfm`
This PR fixes the issue caused by the execution of `_try_source` passing 2 arguments, i.e. that would output as shown above.

fix: 'permission denied' error when executing: plug 'pabloariasal/zfm'

---

zap.zsh

When trying to perform a local file and the file does not exist, :zap: Zap will attempt a Git clone and error.
Modified to check to see if the directory containing the local file exists, if so, then treat as a local source only and not move on should the local file not exist.
For example when executing the below
```
plug "$HOME/.zshrc.local"
```

feat: if plug dirname exists then local source only

---

zap.zsh

It was also called in the wrong way,
probably residue from previous versions

fix: removed useless `_try_source` call

---

README.md
zap.zsh

- Add examples of sourcing local ZSH files via the Zap `plug` function to the README
- Enhance to allow the activating of local plugin directories

feat: cater for sourcing local plugin directories

---

README.md
zap.zsh

I made it so zap will look for a file with one of the extensions `.plugin.zsh`, `.zsh-theme` and `.zsh`. If there is only one such file, zap will source it.
I am pretty sure this will cover most cases where the plugin file doesn't have the same name as the repository, because there's usually only one file with the extensions `.plugin.zsh` or `.zsh-theme` in zsh plugin repositories.
Let me know if I missed anything.
P.S. While working on this, I also found out that zap won't recognize `~` as an alias to `$HOME`, so I added it to Notes in the README.

feat: search for the plugin file to source (close #118)

---

zap.zsh

I found this bug while loading [this](https://github.com/MichaelAquilina/zsh-autoswitch-virtualenv) plugin. Every time I tried to load the plugin I got the following error: 
`❌  zsh-autoswitch-virtualenv not activated`
Turns out that this fix works. Maybe I have an old zsh version or something - but yea it works and I wanted to share with you 😄

Fix: plugin not loading bug

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml
README.md
zap.zsh

- feat: add the ability to change the git clone URL prefix, allowing for SSH keys to be used. 
- feat: update README to be more explicit on how to install local plugins or source local files.
- feat: update README to contain how to use the 'ZAP_GITHUB_PREFIX'.
- feat: update README to contain how to use the 'zap list' command.
- chore: update the github workflow to use the latest versions of the actions.

feat: add git clone URL prefix variable and update documentation

---

zap.zsh

The `try_source` function could use some optimization. The current implementation profiles this way:
```zsh
num  calls                time                       self            name
-----------------------------------------------------------------------------------
1)    2          27.07    13.53   34.68%     27.07    13.53   34.68%  compaudit
2)    9          32.95     3.66   42.22%     23.51     2.61   30.12%  _try_source
3)    1          40.43    40.43   51.81%     13.37    13.37   17.13%  compinit
```
Using NULLGLOB pattern matching to populate a list of possible plugin init files and taking the first element of that list both simplifies the function, and also makes it faster.
```zsh
num  calls                time                       self            name …
```

feat: Speed up plugin source file detection

---

install.zsh
zap.zsh

Modified to perform a `git clone` to be the latest commit only as discussed in Issue #129 
Modified for both installing Zap and installing plugins.
During testing I saw a 35% decrease in the time taken to perform the initial plugin install.

feat: change 'git clone' to be the latest commit only

---

install.zsh

Resolve the following two issues with the Zap installation script
1. Move the check to see if Zap is already installed to before any changes to the .zshrc file are made.
2. Change the launch of a new zsh session to rather reread the .zshrc file to maintain variables, history and allow the install script to be launched from an automation script.  This resolves issue #132

fix: resolve two issues with the Zap installation script

---

zap.zsh

Cleanup the output when performing an update all plugins
Before:
After:

feat: cleanup updating all plugins output

---

install.zsh
zap.zsh

feat: visually show if plugins need to be updated

---

zap.zsh

Executing `zap version` failed due to repository clone with a depth=1 causes the tag to not be visible.
The output after this commit no longer fails and now also outputs the commit date

feat: cleanup and fix version output

---

install.zsh

Dont use ZSHRC variable outside the main() function as no longer in scope.
As reported in issue #134

fix: ZSHRC variable no longer in scope

---

zap.zsh

I make some changes from #123
Please let me know if any changes or improvements are needed, and I'll be happy to make the necessary adjustments. Thank you for considering this contribution!

feat(update): add flag (self, all)

---

install.zsh
zap.zsh

In this PR I changed the `$ZAP_DIR`'s value to the [XDG's standard](https://wiki.archlinux.org/title/XDG_Base_Directory#User_directories) so the zap binary will be installed and used from there.
Warning: this could break the system for people who have a set `$XDG_DATA_HOME` to a non-default value forcing them to move their files/reinstall

feat: use XDG standard path in $ZAP_DIR

---

README.md
zap.zsh

* fix the behavior og ZAP_GITHUB_PREFIX that does not work due to different URL syntax between ssh and http URLs ( fixes #141 )
* allow other git servers besides github and resolves #73
The user have to use `ZAP_GIT_PREFIX` like so:
```zsh
ZAP_GIT_PREFIX='git@gitlab.com:'
```
or
```zsh
ZAP_GIT_PREFIX='git@github.com:'
```
If this variable is not set it defaults to `https://github.com/`.
:warning: please note the trailing `/` or `:`

fix: solve 2 issues #73 and #141

---

.github/workflows/pre-commit.yml
.github/workflows/test-suite.yml
install.zsh
templates/default-zshrc
zap.zsh

- feat: move to use a .zshrc template file
- feat: update to latest github actions version

feat: move to use a .zshrc template file

---

zap.zsh

This will unshallow the clone otherwise no checkout can be done for commits older than head.
fixes #151

fix: unshallow clone for plugin checkout

---

README.md
zap.zsh

In this PR I added the `plugins` option to the `update` command to update only the plugins and changed the `all` option to update all parts (self + plugins)

Change update all to update self plugins

---

install.zsh

- feat: add -k, --keep flags to keep existing .zshrc files   ( resolves #154  and  #148 )
- feat: enhance the argument parsing
- feat: add -h, --help flags to display help message
```
⚡ Zap - Installer
USAGE:
install.zsh [options]
OPTIONS:
-h, --help     Show this help message
-k, --keep     Don't override existing .zshrc
-b, --branch   Zap repository branch name
```

feat: add -k, --keep flags to keep existing .zshrc files

---

zap.zsh

As discussed in Issue #159 
This provides a quick fix to minimise relative directory plug being recognised as local versus performing the expected git clone.

feat: minimise relative directory plug as local versus performing a git clone

---

.github/workflows/test-suite.yml

This should fix the:
```
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
```

fix: `apt install lsd` command in test-suite.yml

---

install.zsh

Support versions of ZSH < 5.8
#169

fix: install.sh: support ZSH(<5.8)

---

README.md
zap.zsh

- Add support for adding all files in a folder if "/*" is included in the given path. For example:
```zsh
plug "$HOME/plugins/*"
```
- For the original functionality I have removed the glob pattern matching there because it is currently not being used since we are only sourcing the 1st element return of `initfiles` array. Instead of creating a loop and be done with it, I decided to look for specific "*" included in the path then do a loop otherwise I just source the 1st element, keeping the original function intact

feat: support glob pattern

---

zap.zsh

fix: correct the method used to obtain the version tag to focus on the current branch not across all branches
Below screenshot of `zap version` showing the new version number when it should be showing the installed version `1.2.1` 
Before and After `git` commands to correct the version number.

fix: correct the method used to obtain the version tag to focus on the current branch not across all branches

---

README.md

Added a tip to the documentation about the optional --keep argument to keep the current .zshrc file. Fixes zap-zsh/zap#184

Documenation Addition
